feat: Add EV charger and car parking agents
fetchai/uAgents-examples pull request #5
Opened 2023-08-03 13:18 UTC by coderlktripathi

This PR introduces two new agents, 'ev_charger' and 'geoapi_car_parking', to enhance mobility services. These agents enable users to find available EV chargers and parking spaces in a specified region using latitude, longitude, and radius parameters.

The 'ev_charger' agent integrates with the OpenChargeMap API to provide real-time data on EV charger availability. On the other hand, the 'geoapi_car_parking' agent leverages the Geoapify API to offer comprehensive information about available parking spaces.

These new agents aim to improve the overall mobility experience, making it easier for users to locate charging stations for their electric vehicles and find suitable parking spots in their vicinity.

2023-08-08 11:05 UTC, GataKamsky commented
@lrahmani / @jrriehl can one of you please review and approve this?

2023-08-09 15:12 UTC, lrahmani requested changes
Looks Good To Me, although the use case is not complete as there are no consumer agents and providers only suggest options. Please check inline comments for more details.

2023-08-09 15:12 UTC, lrahmani commented on mobility-integrations/src/main.py
> +from agents.geopy_car_parking import agent as geopy_car_parking_agent
```suggestion
from agents.geopy_car_parking.geopy_car_parking import agent as geopy_car_parking_agent
```

2023-08-09 15:12 UTC, lrahmani commented on mobility-integrations/src/main.py
> +from agents.geopy_car_parking import agent as geopy_car_parking_agent
`agent` cannot be imported from `agents.geopy_car_parking`.

2023-08-09 15:46 UTC, coderlktripathi commented
@lrahmani fixed import and Readme

2023-08-09 16:17 UTC, lrahmani approved these changes

2023-08-10 13:53 UTC, merged